name: cold_bore
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+36

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  dependencies:
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  ios: true
  android: false
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
